name: Publish

on:
  pull_request:
    types: closed
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: actions/checkout@v1
        with:
          ref: refs/heads/master
      - name: Setup git repo
        run: |
          git config user.name $GITHUB_ACTOR
          git config user.email gh-actions-${GITHUB_ACTOR}@github.com
          git remote add gh-origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: npm install
        run: npm install
      - name: version and publish
        run: |
          npm version minor --force -m "Version %s [build-skip]"
          npm set //registry.npmjs.org/:_authToken $NODE_AUTH_TOKEN
          npm publish
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
      - name: Push release commit and tag to GitHub
        run: git push gh-origin HEAD:master --tags
